### PR TITLE
ACHIEVEMENT GET: ADMIN!

### PR DESCRIPTION
**Pull request by viljow**
this should be self-explanatory smh.

Making me admin to make life easier 🤷‍♂️

### CODE REVIEW

**Comment by strideynet** [comment]
I can't believe I have to merge a pull request with "ACHIEVEMENT GET" in the title.

**Comment by viljow** [comment]
So glad you appreciate my sense of humour 😛

**Comment by strideynet** [comment]
I'm sure sometime someone I work with is going to see this and bully me...

**Comment by viljow** [comment]
oh, almost certainly.

**Pull request merged**
